spring.application.name=CourseRegistrationSystem
# ?? Server ????????????????????????????????????????????????????????????????????
server.port=8080


# ?? Disable Whitelabel Error Page ?????????????????????????????????????????????
server.error.whitelabel.enabled=false

# ?? Jackson JSON ??????????????????????????????????????????????????????????????
spring.jackson.serialization.indent-output=true

# ?? Logging ???????????????????????????????????????????????????????????????????
logging.level.com.example.courseregistrationsystem=DEBUG
